version: '2.2'

networks: {}

volumes: # {{{
  nginx-cache:
    driver: local
  nginx-pid:
    driver: local
  nginx-conf.d:
    driver: local
  phpldapadmin-www:
    driver: local
  phpldappwm-www:
    driver: local
  jenkins_home:
    driver_opts:
      type: none
      device: ${PWD}/jenkins/home
      o: bind
  jenkins-agent_home:
    driver_opts:
      type: none
      device: ${PWD}/jenkins-agent/home
      o: bind
# }}}

services:

  &openldap openldap: # {{{
    extends:
      file: common.yml
      service: common
    image: osixia/openldap:stable
    hostname: *openldap
    command: ["--copy-service"]
    environment:
      - LDAP_ORGANISATION=Example Inc.
      - LDAP_DOMAIN=${LDAP_DOMAIN:-example.org}
      - LDAP_BASE_DN=${LDAP_BASE_DN:-dc=example,dc=org}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD:-admin}
      - LDAP_CONFIG_PASSWORD=config
      - LDAP_READONLY_USER=true
      - LDAP_OPENLDAP_UID=${LDAP_OPENLDAP_UID:-911}
      - LDAP_OPENLDAP_GID=${LDAP_OPENLDAP_GID:-911}
    tty: true
    stdin_open: true
    volumes:
      - ./openldap/ldap:/var/lib/ldap
      - ./openldap/slapd.d:/etc/ldap/slapd.d
      - ./openldap/certs:/container/service/slapd/assets/certs/
      - ./openldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom:ro
  # }}}

  &phpldapadmin phpldapadmin: # {{{
    extends:
      file: common.yml
      service: common
    build:
      context: ./phpldapadmin/build
    image: nakahiro386/phpldapadmin-ja:stable
    hostname: *phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: *openldap
    depends_on:
      - *openldap
    volumes:
      - phpldapadmin-www:/var/www/phpldapadmin
  # }}}

  &phpldappwm phpldappwm: # {{{
    extends:
      file: common.yml
      service: common
    build:
      context: ./phpldapadmin/build
    image: nakahiro386/phpldapadmin-ja:stable
    command: ["--copy-service"]
    hostname: *phpldappwm
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: *openldap
      PHPLDAPADMIN_SERVER_PATH: "/phpldappwm"
    depends_on:
      - *openldap
    volumes:
      - phpldappwm-www:/var/www/phpldapadmin
      - ./phpldapadmin/config/config.php:/container/service/phpldapadmin/assets/config/config.php:ro
  # }}}

  &portainer portainer: # {{{
    extends:
      file: common.yml
      service: common
    image: portainer/portainer-ce:2.11.0
    hostname: *portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer/data:/data
    depends_on:
      - *openldap
  # }}}

  &gb-postgres gb-postgres: # {{{
    extends:
      file: common.yml
      service: common
    image: postgres:14-alpine
    hostname: *gb-postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${GITBUCKET_POSTGRES_USER:-gitbucket}
      POSTGRES_PASSWORD: ${GITBUCKET_POSTGRES_PASSWORD:-gitbucket}
    volumes:
      - ./gb-postgres/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "5432"]
  # }}}

  &gitea-db gitea-db: # {{{
    extends:
      file: common.yml
      service: common
    image: postgres:13-alpine
    hostname: *gitea-db
    environment:
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ${GITEA_POSTGRES_DB:-gitea}
      POSTGRES_USER: ${GITEA_POSTGRES_USER:-gitea}
      POSTGRES_PASSWORD: ${GITEA_POSTGRES_PASSWORD:-gitea}
    volumes:
      - ./gitea-db/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "5432"]
  # }}}

  &gitbucket gitbucket: # {{{
    extends:
      file: common.yml
      service: common
    image: gitbucket/gitbucket:4.36.1
    hostname: *gitbucket
    command: ["java", "-jar", "/opt/gitbucket.war"]
    stop_signal: SIGINT
    environment:
      GITBUCKET_BASE_URL: https://${SSL_SUBJECT:-$HOSTNAME}:${NGINX_SSL_PORT:-443}/gitbucket
      # GITBUCKET_PORT: ${GITBUCKET_PORT:-8080}
      GITBUCKET_PREFIX: /gitbucket
      GITBUCKET_PLUGINDIR: /plugin
      GITBUCKET_SAVE_SESSIONS: "True"
      GITBUCKET_DB_URL: jdbc:postgresql://gb-postgres/gitbucket
      GITBUCKET_DB_USER: ${GITBUCKET_POSTGRES_USER:-gitbucket}
      GITBUCKET_DB_PASSWORD: ${GITBUCKET_POSTGRES_PASSWORD:-gitbucket}

      # System settings
      GITBUCKET_ALLOW_ACCOUNT_REGISTRATION: "False"
      GITBUCKET_IS_CREATE_REPOSITORY_OPTION_PUBLIC: "True"
      GITBUCKET_ALLOW_ANONYMOUS_ACCESS: "False"
      GITBUCKET_LIMIT_VISIBLE_REPOSITORIES: "True"
      GITBUCKET_ACTIVITY_LOG_LIMIT: 100

      # integrations
      ## SSH access
      GITBUCKET_GRAVATAR: "False"
      GITBUCKET_SSH: "True"
      GITBUCKET_SSH_HOST: ${SSL_SUBJECT:-$HOSTNAME}
      GITBUCKET_SSH_PORT: ${GITBUCKET_SSH_PORT:-29418}
      ## Communication
      GITBUCKET_USE_SMTP: "False"
      GITBUCKET_USE_SMTP_HOST: maildev
      GITBUCKET_USE_SMTP_PORT: 25
      GITBUCKET_USE_SMTP_FROM_ADDRESS: gitbucket@example.org
      GITBUCKET_USE_SMTP_FROM_NAME: gitbucket
      ## Notifications
      GITBUCKET_NOTIFICATION: "False"

      # authentication
      GITBUCKET_LDAP_AUTHENTICATION: "True"
      GITBUCKET_LDAP_HOST: *openldap
      GITBUCKET_LDAP_PORT: 389
      GITBUCKET_LDAP_BINDDN: "cn=admin,${LDAP_BASE_DN:-dc=example,dc=org}"
      GITBUCKET_LDAP_BIND_PASSWORD: ${LDAP_ADMIN_PASSWORD:-admin}
      GITBUCKET_LDAP_BASEDN: "ou=Users,${LDAP_BASE_DN:-dc=example,dc=org}"
      GITBUCKET_LDAP_USERNAME_ATTRIBUTE: uid
      GITBUCKET_LDAP_FULLNAME_ATTRIBUTE: displayName
      GITBUCKET_LDAP_MAIL_ATTRIBUTE: mail
    volumes:
      - ./gitbucket/data:/gitbucket
      - ./gitbucket/plugin:/plugin
    ports:
      # - ${GITBUCKET_PORT:-8080}:${GITBUCKET_PORT:-8080}
      - ${GITBUCKET_SSH_PORT:-29418}:${GITBUCKET_SSH_PORT:-29418}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "-O", "/dev/null", "http://127.0.0.1:8080/gitbucket/signin"]
      retries: 10
    depends_on:
      - *gb-postgres
  # }}}

  &gitea gitea: # {{{
    extends:
      file: common.yml
      service: common
    image: gitea/gitea:1.15.6
    hostname: *gitea
    environment:
      USER_UID: ${GITEA_USER_UID:-1000}
      USER_GID: ${GITEA_USER_GID:-1000}
      GITEA__server__ROOT_URL: https://${SSL_SUBJECT:-$HOSTNAME}:${NGINX_SSL_PORT:-443}/git
      GITEA__server__SSH_PORT: ${GITEA_SSH_PORT:-222}
      GITEA__server__OFFLINE_MODE: "true"
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: gitea-db:5432
      GITEA__database__NAME: ${GITEA_POSTGRES_DB:-gitea}
      GITEA__database__USER: ${GITEA_POSTGRES_USER:-gitea}
      GITEA__database__PASSWD: ${GITEA_POSTGRES_PASSWORD:-gitea}
      GITEA__picture__DISABLE_GRAVATAR: "true"
      GITEA__picture__ENABLE_FEDERATED_AVATAR: "false"
      GITEA__service__DISABLE_REGISTRATION: "true"
      GITEA__service__REQUIRE_SIGNIN_VIEW: "true"
      GITEA__service__REGISTER_EMAIL_CONFIRM: "false"
      GITEA__service__ENABLE_NOTIFY_MAIL: "false"
      GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION: "false"
      GITEA__service__ENABLE_CAPTCHA: "false"
      GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE: "false"
      GITEA__service__DEFAULT_ALLOW_CREATE_ORGANIZATION: "true"
      GITEA__service__DEFAULT_ENABLE_TIMETRACKING: "true"
      GITEA__mailer__ENABLED: "false"
      GITEA__openid__ENABLE_OPENID_SIGNIN: "false"
      GITEA__openid__ENABLE_OPENID_SIGNUP: "false"
      GITEA__cron.sync_external_users__ENABLED: "true"
      GITEA__cron.sync_external_users__RUN_AT_START: "true"
      GITEA__cron.sync_external_users__SCHEDULE: "@every 1h"
      GITEA__log__LEVEL: debug
    volumes:
      - ./gitea:/data
    ports:
      - ${GITEA_SSH_PORT:-222}:22
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "-O", "/dev/null", "http://127.0.0.1:3000/"]
      retries: 10
    depends_on:
      - *gitea-db
  # }}}

  group-sync: # {{{
    container_name: gitea-group-sync
    image: ghcr.io/gitea-group-sync/gitea-group-sync:master
    environment:
      GITEA_TOKEN: ${GITEA_TOKEN}
      GITEA_URL: http://gitea:3000
      LDAP_URL: *openldap
      LDAP_PORT: 389
      BIND_DN: cn=admin,dc=example,dc=org
      BIND_PASSWORD: admin
      LDAP_FILTER: '(&(objectClass=posixAccount)(memberOf=cn=%s,ou=Groups,dc=example,dc=org))'
      LDAP_USER_SEARCH_BASE: 'ou=Users,dc=example,dc=org'
      LDAP_USER_FULL_NAME: 'cn'
      REP_TIME: '@every 1h'
    depends_on:
      - *gitea
      - *openldap
  # }}}

  &jenkins jenkins: # {{{
    extends:
      file: common.yml
      service: common
    build:
      context: ./jenkins/build
      args:
        SSL_SUBJECT: ${SSL_SUBJECT}
        NGINX_SSL_PORT: ${NGINX_SSL_PORT}
    image: nakahiro386/jenkins:lts
    volumes:
      - jenkins_home:/var/jenkins_home:rw
    hostname: *jenkins
    environment:
      SSL_SUBJECT: ${SSL_SUBJECT:-$HOSTNAME}
      NGINX_SSL_PORT: ${NGINX_SSL_PORT:-443}
      LDAP_HOSTS: *openldap
      LDAP_BASE_DN: ${LDAP_BASE_DN:-dc=example,dc=org}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-admin}
    depends_on:
      - *openldap
  # }}}

  &jenkins-agent jenkins-agent: # {{{
    extends:
      file: common.yml
      service: common
    build:
      context: ./jenkins-agent/build
      args:
        SSL_SUBJECT: ${SSL_SUBJECT}
        NGINX_SSL_PORT: ${NGINX_SSL_PORT}
    image: nakahiro386/jenkins-agent:openjdk8-buster
    volumes:
      - jenkins-agent_home:/home/jenkins-agent:rw
    hostname: *jenkins-agent
    environment:
      JENKINS_URL: http://jenkins:8080/jenkins/
      AGENT_USERNAME: agent
      AGENT_PASSWORD: agent
      AGENT_PROMETHEUS_PORT: ${AGENT_PROMETHEUS_PORT:-9100}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "-O", "/dev/null", "http://127.0.0.1:${AGENT_PROMETHEUS_PORT:-9100}/prometheus"]
      retries: 30
    depends_on:
      - *jenkins
  # }}}

  &nginx nginx: # {{{
    extends:
      file: common.yml
      service: common
    image: nginx:stable-alpine
    hostname: *nginx
    read_only: true
    ports:
      - ${NGINX_PORT:-80}:${NGINX_PORT:-80}
      - ${NGINX_SSL_PORT:-443}:${NGINX_SSL_PORT:-443}
    environment:
      - NGINX_PORT=${NGINX_PORT:-80}
      - NGINX_SSL_PORT=${NGINX_SSL_PORT:-443}
    volumes:
      - nginx-cache:/var/cache/nginx
      - nginx-pid:/var/run
      - nginx-conf.d:/etc/nginx/conf.d
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./certs:/etc/nginx/ssl:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "-O", "/dev/null", 'http://127.0.0.1:${NGINX_PORT}/']
      retries: 10
    depends_on:
      - *phpldapadmin
      - *portainer
      - *gitbucket
      - *gitea
      - *jenkins
  # }}}

  &ansible-run ansible-run: # {{{
    extends:
      file: common.yml
      service: common
    restart: "no"
    build:
      context: ./ansible
      args:
        ANSIBLE_EXEC_UID: "${ANSIBLE_EXEC_UID:-1000}"
        ANSIBLE_EXEC_USER: "${ANSIBLE_EXEC_USER:-ansible}"
        ANSIBLE_EXEC_GID: "${ANSIBLE_EXEC_GID:-1000}"
        ANSIBLE_EXEC_GROUP: "${ANSIBLE_EXEC_GROUP:-ansible}"
    image: nakahiro386/ansible-ldap:latest
    tty: true
    volumes:
      - ./ansible:/ansible:rw
    working_dir: /ansible
    command: ["ansible-playbook", "playbook.yml"]
    hostname: *ansible-run
    environment:
      LDAP_HOSTS: *openldap
      LDAP_BASE_DN: ${LDAP_BASE_DN:-dc=example,dc=org}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-admin}
    depends_on:
      - *openldap
  # }}}


# vim:set filetype=docker-compose expandtab shiftwidth=2 tabstop=2 foldmethod=marker:
