<?php
/** NOTE **
 ** Make sure that <?php is the FIRST line of this file!
 ** IE: There should NOT be any blank lines or spaces BEFORE <?php
 **/

 /*********************************************
  * Useful important configuration overrides  *
  *********************************************/

 /* If you are asked to put PLA in debug mode, this is how you do it: */
 $config->custom->debug['level'] = 0;
 $config->custom->debug['syslog'] = true;
 #  $config->custom->debug['file'] = '/tmp/pla_debug.log';

/**
 * The phpLDAPadmin config file
 * See: http://phpldapadmin.sourceforge.net/wiki/index.php/Config.php
 */

/* The temporary storage directory where we will put jpegPhoto data
   This directory must be readable and writable by your web server. */
 $config->custom->jpeg['tmpdir'] = '/var/www/tmp';

 /* phpLDAPadmin can encrypt the content of sensitive cookies if you set this
   to a big random string. */

/*
 * Autogenerated value will be automatically added by phpldapadmin/startup.sh
 */
 $config->custom->session['blowfish'] = '{{ PHPLDAPADMIN_CONFIG_BLOWFISH }}';


/*********************************************
 * Appearance                                *
 *********************************************/
/* Hide the warnings for invalid objectClasses/attributes in templates. */
$config->custom->appearance['hide_template_warning'] = true;


$config->custom->appearance['readonly_attrs'] = array(
  'cn',
  'mail',
  'uid',
  'uidNumber',
  'gidNumber',
  'homeDirectory'
);
$config->custom->appearance['attr_display_order'] = array(
  'cn',
  'mail',
  'userPassword',
  'sshPublicKey',
  'uid',
  'uidNumber',
  'gidNumber',
  'homeDirectory',
  'givenName',
  'sn',
  'displayName'
);
$config->custom->appearance['hide_attrs'] = array(
  'objectClass'
);
// $config->custom->appearance['tree_filter'] = '(ou=Users)';
$config->custom->appearance['minimalMode'] = true;
// $config->custom->confirm['update'] = false;

/*********************************************
 * User-friendly attribute translation       *
 *********************************************/

/* Use this array to map attribute names to user friendly names. For example, if
   you don't want to see "facsimileTelephoneNumber" but rather "Fax". */
// $config->custom->appearance['friendly_attrs'] = array();
$config->custom->appearance['friendly_attrs'] = array(
	'facsimileTelephoneNumber' => 'Fax',
	'gid'                      => 'Group',
	'mail'                     => 'Email',
	'telephoneNumber'          => 'Telephone',
	'uid'                      => 'User Name',
	'userPassword'             => 'Password'
);


/*********************************************
 * Define your LDAP servers in this section  *
 *********************************************/

$servers = new Datastore();

/*
 * Autogenerated servers variables will come here
 */
{{ PHPLDAPADMIN_SERVERS }}

$servers->setValue('login','bind_id','cn=admin,dc=example,dc=org');
$servers->setValue('login','bind_pass','admin');
$servers->setValue('login','attr','uid');
$servers->setValue('login','fallback_dn',false);
$servers->setValue('server','read_only',false);
